In [1]:
import tkinter as tk
import numpy as np
from math import ceil
import tkinter.messagebox
from os import makedirs
from os import path
from time import strftime
import re
import copy
import time
import hashlib
import shelve
import os

In [2]:
class gameboard:  
    
    def __init__(self,board = None, end = False, overallpoint = 0):
        if board is None:
            self.board = np.zeros((15,15),dtype = int)
        else:
            self.board = board

        self.end = end
        self.overallpoint = overallpoint
    
    def get_board(self):
        return self.board
    
    def update_point(self,point):
        self.overallpoint += point
        
    def get_overallpoint(self):
        return self.overallpoint
    
    def set_overallpoint(self,point):
        self.overallpoint = point
    
    def get_end(self):
        return self.end
    
    def set_end(self,state):
        self.end = state
    
  
    def empty_all(self):
        self.board = np.zeros((15,15),dtype = int) #清空矩阵
        
    def empty_one(self,row, col):
        self.board[row][col] = 0
    
    def add_black_piece(self,row,col):
        if not self.occupied(row,col):
            self.board[row][col] = 1
        
    def add_white_piece(self,row,col):
        if not self.occupied(row,col):
            self.board[row][col] = 2
        
    def occupied(self,row,col):
        if self.board[row][col] == 0:
            return False
        else:
            return True
    
    def getline_point(self,row,col):
        lines = []
        point_parameter = [['line_0',0,+1],
                              ['line_45',-1,1],
                              ['line_90',+1,0],
                              ['line_135',-1,-1]]
        for direction in point_parameter:
            line = ''
            for i in range(-5,6):
                current_row = row + direction[1]*i
                current_col = col + direction[2]*i
                if current_row in range(15) and current_col in range(15):
                    line = line + str(self.board[current_row][current_col])
                else:
                    line = line + str(3)
            lines.append(line)
        return lines

    
    def if_end(self,row,col):    
        lines = self.getline_point(row,col)
        if_end = False
        for line in lines:
            result = re.findall('(11111|22222)',line)
            if result:
                self.set_end(True)
        

    
    def getline_all(self):
        #point = 0
        lines = []
        for row in range(15):
            line_0 = ''
            for col in range(15):
                line_0 = line_0 + str(self.board[row][col])
            lines.append(line_0)
            #lines.append((line_0,(row,'x')))
                         
        for i in range(1,11,1): 
            baserow = 14 
            basecol = i 
            line_45 = ''
            for m in range(15):
                nextrow = baserow - m
                nextcol = basecol + m
                if nextrow in range(15) and nextcol in range(15):
                    line_45 = line_45 + str(self.board[nextrow][nextcol])
                else:
                    line_45 = line_45 + '3'
            lines.append(line_45)
            #lines.append((line_45,(baserow,basecol)))
                         
        for i in range(4,15): 
            baserow = 0 
            basecol = i 
            line_45 = ''
            for m in range(15):
                nextrow = baserow + m
                nextcol = basecol - m
                if nextrow in range(15) and nextcol in range(15):
                    line_45 = line_45 + str(self.board[nextrow][nextcol])
                else:
                    line_45 = line_45 + '3'
            lines.append(line_45)
            #lines.append((line_45,(baserow,basecol)))
                         
        for col in range(15):
            line_90 = ''
            for row in range(15):
                line_90 = line_90 + str(self.board[row][col])
            lines.append(line_90)
            #lines.append((line_90,('x',col)))
                         
        for i in range(11):
            baserow = 0
            basecol = i 
            line_135 = ''
            for m in range(15):
                nextrow = baserow + m
                nextcol = basecol + m
                if nextrow in range(15) and nextcol in range(15):
                    line_135 = line_135 + str(self.board[nextrow][nextcol])
                else: 
                    line_135 = line_135 + '3'
            lines.append(line_135)
            #lines.append((line_135,(baserow,basecol)))
                         
        for i in range(4,14,1):
            baserow = 14 
            basecol = i 
            line_135 = ''
            for m in range(15):
                nextrow = baserow - m
                nextcol = basecol - m
                if nextrow in range(15) and nextcol in range(15):
                    line_135 = line_135 + str(self.board[nextrow][nextcol])
                else: 
                    line_135 = line_135 + '3'
            lines.append(line_135) 
            #lines.append((line_135,(baserow,basecol)))
        return lines

        
        
        
        
        
if __name__ == '__main__':     
    board = gameboard()
    board.add_black_piece(7,7)
    board.add_white_piece(6,7)
    board.add_black_piece(6,6)
    board.add_white_piece(7,6)
    board.add_black_piece(5,5)
    
    print(board.get_end())
    board.add_white_piece(5,8)
    board.add_black_piece(8,8)
    board.add_white_piece(8,5)
    board.add_black_piece(4,4)
    board.if_end(4,4)
    print(board.get_end())
    print(board.get_board())

False
True
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 2 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 2 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 2 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 2 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]


In [3]:
class player:
    def __init__(self,name,on_white):
        self.name = name  
        self.on_white = on_white
    
        
    
    def get_name(self):
        return self.name

    def set_name(self,name):
        self.name = name
    
    def get_on_white(self):
        return self.on_white
    
if __name__ == '__main__':     
    pass


In [4]:
class human(player):
    def __init__(self,name='Default User',contact='******',on_white=False):
        player.__init__(self,name,on_white)
        self.contact = contact
        
    def ask_coordinate(self):
        row = int(input('row:'))
        col = int(input('col:'))
        return (row,col)
    
    def get_contact(self):
        return self.contact
    
    def set_contact(self,contact):
        self.contact = contact
    
    
if __name__ == '__main__':     
    #pass
    pl = human()
    c = pl.get_contact()
    print(c)
    cc= pl.set_contact('2333')
    print(cc)
    p2 = human()
    
    
    #pl.ask_coordinate()    

******
None


In [51]:

class AI(player):
    def __init__(self,name = 'Alpha Yi',intelligence = 3,on_white = True):
        player.__init__(self,name,on_white)
        self.intelligence = intelligence
        self.adv = 0
        self.assignments_b = [('活2',60),  ('冲2',30),  ('活3',1500),  ('冲3',300),  ('夹3',300),  
                            ('活4',6750),  ('冲4',1500),  ('偏夹4',1500),  ('正夹4',1500),  ('五连',150000)] 
        
        self.assignments_w = [('活2',40),  ('冲2',20),  ('活3',1000),  ('冲3',200),  ('夹3',200),  
                            ('活4',4500),  ('冲4',1000),  ('偏夹4',1000),  ('正夹4',1000),  ('五连',100000)] 
        #('截活2',-40),('截冲2',-20),('截活3',-320),('截冲3',-160),('截夹3',-170),('截活4',-2500),('截冲4',-1500),('截偏夹4',-1400),('截正夹4',-1600)
        self.dir_path = path.join(path.expanduser('~'),'Desktop','AlphaYi')
        self.fullpath = path.join(self.dir_path,'HashTable')
        if not path.exists(self.dir_path): 
            makedirs(self.dir_path)
        
    def set_intelligence(self,intelligence):
        self.intelligence = intelligence
        
    def get_intelligence(self): 
        return self.intelligence
    def base_point(self,row,col): # 某一位置的base point
        return (7 - abs(row-7))+(7-abs(col-7))    
    def get_base_all(self,board): #当前棋局的base point
        point = 0
        board_c = board.get_board()
        for row in range(15):
            for col in range(15):
                if board_c[row][col] == 1:
                    point -= self.base_point(row,col)
                if board_c[row][col] == 2:
                    point += self.base_point(row,col)
        return point
    

    
    def evaluate_black(self,line): #对某一方向上的黑棋做评估，返回评估分数以及是否形成五连（黑棋越占优，分数越低）
        point = 0
        blackplays = []
        if_end = False
        blackplays.append(re.findall('([023]01100|00110[023])',line)) #活2
        blackplays.append(re.findall('([23]11000|00011[23]｜)',line)) #冲2
        blackplays.append(re.findall('(01110[023]|[023]01110)',line)) #活3
        blackplays.append(re.findall('([23]1110|0111[23])',line)) #冲3
        blackplays.append(re.findall('(01101[023]|[023]10110|[023]01011|11010[023])',line)) #夹3
        blackplays.append(re.findall('(011110)',line)) #活4
        blackplays.append(re.findall('(11112|21111)',line)) #冲4
        blackplays.append(re.findall('(10111|11101)',line)) #偏夹4
        blackplays.append(re.findall('(11011)',line)) #正夹4
        blackplays.append(re.findall('(11111)',line)) #五连
        #print('balckplayes::',blackplays)#####
        for i in range(10): 
            if blackplays[i]:  
                if i == 9:
                    if_end = True
                point -= (self.assignments_b[i][1]+self.adv)
        return (point,if_end)       
    
    def evaluate_white(self,line): #对某一方向上的白棋做评估，返回评估分数以及是否形成五连（白棋越占优，分数越低）
        point = 0
        whiteplays = []
        if_end = False
        whiteplays.append(re.findall('([013]02200|00220[013])',line)) #活2
        whiteplays.append(re.findall('([13]22000|00022[13])',line)) #冲2
        whiteplays.append(re.findall('(02220[013]|[013]02220)',line)) #活3
        whiteplays.append(re.findall('([13]2220|0222[13])',line)) #冲3
        whiteplays.append(re.findall('(02202[013]|[013]20220|[013]02022|22020[013])',line)) #夹3
        whiteplays.append(re.findall('(022220)',line)) #活4
        whiteplays.append(re.findall('(22221|12222)',line)) #冲4
        whiteplays.append(re.findall('(20222|22202)',line)) #偏夹4
        whiteplays.append(re.findall('(22022)',line)) #正夹4
        whiteplays.append(re.findall('(22222)',line)) #五连
        #print('whiteplayes::',whiteplays)#####
        for i in range(10): 
            if whiteplays[i]:  
                if i == 9:
                    if_end = True
                point += self.assignments_w[i][1]      
        return (point,if_end)
    
    def evaluate_board(self,board):#对
        base = self.get_base_all(board) #根据占位获取基本分数
        lines = board.getline_all()     #对全棋盘全部方向取样
        if_end = False     
        total_point = 0
        for line in lines:              #对黑白棋分别得到（评估分数，是否五连）
            temp_point1, temp_if_end1 = self.evaluate_white(line)
            temp_point2, temp_if_end2 = self.evaluate_black(line)
            total_point += temp_point1
            total_point += temp_point2
            if temp_if_end1 or temp_if_end2:
                if_end = True
        total_point += base             #评估分数加上占位基本分
        return (total_point, if_end)
    
    
    def evaluation_pipeline_white(self,board,row,col): #下某步棋后 场面的静态分数变化  
        base = self.base_point(row,col)
        lines = board.getline_point(row,col)           #返回变化的分数 以及此棋落下后是否形成五连
        total_point_changed = 0
        if_end = False
        for line in lines:
            point = 0
            point_played = 0
            line_played = line[:5] + str(2) + line[6:]  
            point += self.evaluate_white(line)[0]  
            point += self.evaluate_black(line)[0]
            point_played += self.evaluate_black(line_played)[0]
            temp_point,temp_if_end = self.evaluate_white(line_played)
            point_played += temp_point
            if temp_if_end:
                if_end = True
            point_changed = point_played - point
            total_point_changed += point_changed
        total_point_changed += base
        return (total_point_changed,if_end)
        
        
    def evaluation_pipeline_black(self,board,row,col): #下某步棋后 场面的静态分数变化 
        base = self.base_point(row,col)
        lines = board.getline_point(row,col)           #返回变化的分数 以及此棋落下后是否形成五连
        total_point_changed = 0
        if_end = False
        for line in lines:
            point = 0
            point_played = 0
            line_played = line[:5] + str(1) + line[6:]  
            point += self.evaluate_white(line)[0]  
            point += self.evaluate_black(line)[0]
            point_played += self.evaluate_white(line_played)[0]
            temp_point,temp_if_end = self.evaluate_black(line_played)
            point_played += temp_point
            if temp_if_end:
                if_end = True
            point_changed = point_played - point
            total_point_changed += point_changed
        total_point_changed -= base
        return (total_point_changed,if_end)
  
    def get_child_white(self,board,row,col):     #获取当前棋盘下某步棋后的子棋盘 
        point_changed, if_end = self.evaluation_pipeline_white(board,row,col)
        array = board.get_board()
        array_copy = copy.deepcopy(array)
        array_copy[row][col] = 2
        child = gameboard(array_copy,if_end,board.get_overallpoint()+point_changed)
        return child


    def get_child_black(self,board,row,col):     #获取当前棋盘下某步棋后的子棋盘
        point_changed, if_end = self.evaluation_pipeline_black(board,row,col)
        array = board.get_board()
        array_copy = copy.deepcopy(array)
        array_copy[row][col] = 1
        child = gameboard(array_copy,if_end,board.get_overallpoint()+point_changed)
        return child    
    
    def get_order_list(self,row,col):  #获取以当前重心为中心开始的序列
        order_list = []
        go_down = [1,0]
        go_up = [-1,0]
        go_left = [0,-1]
        go_right = [0,1]
        go_set = [go_right,go_down,go_left]

        for i in range(15):
            current = (row-i,col-i)
            if current[0] in range(15) and current[1] in range(15):
                order_list.append(current)

            for go in go_set:
                for n in range(i*2):
                    current = (current[0]+go[0], current[1]+go[1])
                    if current[0] in range(15) and current[1] in range(15):
                        order_list.append(current)  
            for n in range(i*2-1):
                current = (current[0]+go_up[0], current[1]+go_up[1])
                if current[0] in range(15) and current[1] in range(15):
                    order_list.append(current)
        return order_list
       
        
    def piece_nearby(self,board,row,col):
        for i in range(-2,3):
            for l in range(-2,3):
                test_row = row+i
                test_col = col+l
                if test_row in range(15) and test_col in range(15):
                    if board.occupied(row+i,col+l):
                        return True
        return False
        
        
    def get_density_center(self,board): #获取重心
        net_row = 0
        net_col = 0
        count = 0
        for row in range(15):
            for col in range(15):
                if board.occupied(row,col):
                    net_row += row
                    net_col += col
                    count += 1
        #print('density center***********',int(net_row/count), int(net_col/count))
        return (int(net_row/count), int(net_col/count))
    
    
    def hashing(self,board): #获取棋盘对应的哈希值
        hashing = hashlib.md5()
        hashing.update(str(board.get_board()).encode('utf-8'))
        return hashing.hexdigest()
    
    
    def recall(self,board): #通过哈希值找寻之前相同的棋局，（（point，coordinate），deepth，count）
        key = self.hashing(board)
        with shelve.open(self.fullpath) as hm:
            value = hm.get(key)
            if value:
                value[2] += 1
                hm[key] = value
                return value
    
    def remember(self,board,point,deepth): #记住当前棋局的哈希值{‘哈希值’：（（分数，为了达成需要走的位置），考虑深度，使用次数计数）}
        key = self.hashing(board)
        value = [point,deepth,1]
        with shelve.open(self.fullpath) as hm:
            hm[key] = value
    
    def minimax(self, board, intelligence, alpha, beta,order=(-1,-1),ifwhite = True): #获得当前棋盘若干回合后的静态分数
        if intelligence == 0 or board.end:         #如果深度为0，或者此棋盘形成五连/结束
            return (board.get_overallpoint(),order) # 就返回当前棋盘的静态分数，以及返回形成此子棋盘的这步棋。（分数，某步棋）
        else:
            value =  self.recall(board)              #如果不为0，检查是否曾经见过这个局面 
            if value:                                  #如果见过 返回【（分数，某步棋），deepth，count】？？
                if value[1] >= intelligence:          #如果深度比当前需求还高，那直接返回分数
                    return value[0]                 
                                                  
        if ifwhite:                                  #如果没见过 且当前落子者为白色
            maxvalue = (-float("inf"),(0,0))         #把最大值重置为无限小
            center = self.get_density_center(board)   #测出当前棋盘的重心
            order_list = self.get_order_list(center[0],center[1]) #根据重心列出 测试坐标 顺序
            for order in order_list:                        
                if not board.occupied(order[0],order[1]):        #如果该坐标没被占据
                    if not self.piece_nearby(board,order[0],order[1]):  #附近两格内没棋子 则不考虑
                        continue
                    child = self.get_child_white(board,order[0],order[1])  #生成该坐标落白子后的子棋盘
                    point = self.minimax(child, intelligence-1,alpha,beta,order,False)  #计算当前子棋盘考虑（若干-1）回合后的静态分数
                    if maxvalue[0] < point[0]:      #记录最高的子棋盘的静态分数（因为白棋会选择最高分数的子棋盘）
                        maxvalue = (point[0],order)     #（最低分数，为了达到有此分数的子棋盘白方要走的这步棋）   
                    alpha = max(alpha,point[0])         #提升下限为目前最高的静态分数，
                    if beta <= alpha:                   #上限超过下限这个后面就不会有合适的解了
                        break

            self.remember(board,maxvalue,intelligence)  #记录1.当前棋盘以及 2.（考虑到X步后的最大分数，达成这分数的子棋盘走法）3.考虑了X步
            return maxvalue                             #返回（分数，落子坐标）
        else:                                 
            minvalue = (+float("inf"),(-1,-1))          #把最小值重置为无限小
            center = self.get_density_center(board)     #测重心
            order_list = self.get_order_list(center[0],center[1]) #根据重心列出 测试坐标 顺序
            for order in order_list:
                if not board.occupied(order[0],order[1]):        #如果该坐标没被占据
                    if not self.piece_nearby(board,order[0],order[1]):  #附近两格内没棋子 则不考虑
                        continue
                    child = self.get_child_black(board,order[0],order[1])     #生成该坐标落黑子后的子棋盘
                    point = self.minimax(child, intelligence-1,alpha,beta,order,True)   #计算当前子棋盘的（若干-1）回合后的静态分数
                    if minvalue[0] > point[0]:     #记录子棋盘中最低的静态分数（分数越低对于黑棋来说越是好棋）
                        minvalue = (point[0],order)     #（最低分数，到达此有分数的子棋盘黑方需的这步棋）
                    beta = min(beta,point[0])
                    if beta <= alpha:
                        break
            self.remember(board,minvalue,intelligence)   ##记录1.当前棋盘以及 2.（考虑到X步后的最小分数，达成这分数的子棋盘走法）3.考虑了X步
            return minvalue
#关于历史启发        
#        
#关于剪枝        
#最开始上限beta和下限alpha都是无限，因为白棋会选所有子棋盘中的最大值的坐标， 一旦知道某个子棋盘的值，那么所有比这个子棋盘小的子棋盘
#都不会再被选到，所以白棋方选择子棋盘的因素与下限有关（至少会选择x分的子棋盘）， 同理黑色方选择因素只考虑上线（最多会选择x分的子棋盘）
#母盘的白方会选择至少x分，那么子盘的黑方一旦上限为x-1（最多也只能选出x-1分的棋盘），那么后面的子盘就不用再考虑了。（达成剪枝条件） 
#关于深度（ai智力）    
#如果intell = 2，白子将会对每一个空格尝试下子，每下一个子后，黑方会在剩余的每个空格上下子并返还（能找到的最小的值，达成
#这最小值的黑棋坐标），白方在尝试完所有选项后，在所有黑方返回的最小值中选一个最大的值并返回（最小值中最大的值，达成这最大值所在的坐标）
#如果intell = 3，白子会将会对每个空格尝试下子，每下一个子后，黑方会对剩下的每个空格尝试下子，白方会返回算出后的最大值。黑方在白方
#给的最大值中找出最小的值给控制母棋盘的白子，白子最后在所有黑子提供的最小值中找出最大的值并返回（最小值中最大的值，达成这最大值所在的坐标）
    

    def think(self,board):
        output = self.minimax(board,self.intelligence,-float("inf"),+float("inf"),(-1,-1),self.get_on_white())
        return output[1]
        
    def ask_coordinate(self):
        row = int(input('row:'))
        col = int(input('col:'))
        return (row,col)    

        
if __name__ == '__main__':  
    pass
    ai = AI()
    board = gameboard()
    board.add_black_piece(6, 7)
    board.add_white_piece(7, 7)
    board.add_black_piece(7, 6)
    board.add_white_piece(5, 8)
    board.add_black_piece(6, 6)
    board.add_white_piece(6, 8)
    board.add_black_piece(5, 6)
    board.add_white_piece(8, 6)
    board.add_black_piece(4, 6)
    board.add_white_piece(3, 6)
    board.add_black_piece(5, 9)
    board.add_white_piece(9, 5)
    board.add_black_piece(10, 4)
    board.add_white_piece(7, 8)
    board.add_black_piece(4, 8)
    board.add_white_piece(8, 8)
    board.add_black_piece(9, 8)
    board.add_white_piece(4, 7)
    board.add_black_piece(6, 9)
    board.add_white_piece(2, 5)
    board.add_black_piece(1, 4)
    board.add_white_piece(8, 7)
    board.add_black_piece(8, 9)
#     board.add_white_piece(8, 5)
#     board.add_black_piece(8, 4)
#     board.add_white_piece(7, 9)
#     board.add_black_piece(7, 5)
#     board.add_white_piece(5, 7)
#     board.add_black_piece(9, 3)
#     board.add_white_piece(10, 2)
#     board.add_black_piece(9, 4)
#     board.add_white_piece(8, 10)
#     board.add_black_piece(9, 11)
#     board.add_white_piece(7, 10)
#     board.add_black_piece(7, 4)
#     board.add_white_piece(7, 11)
    print(board.get_board())

#     m = ai.minimax_v1(board,3,-float("inf"),+float("inf"),(-1,-1))
#     print(m)

   # start = time.clock()

   # end = time.clock()
    #print(end - start)
    
#  self.assignments_b = [('活2',60),  ('冲2',30),  ('活3',1500),  ('冲3',300),  ('夹3',300),  
#                             ('活4',6750),  ('冲4',1500),  ('偏夹4',1500),  ('正夹4',1500),  ('五连',150000)] 
        
#   self.assignments_w = [('活2',40),  ('冲2',20),  ('活3',1000),  ('冲3',200),  ('夹3',200),  
#                             ('活4',4500),  ('冲4',1000),  ('偏夹4',1000),  ('正夹4',1000),  ('五连',100000)] 
    

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 2 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 2 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 2 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 2 1 0 0 0 0 0]
 [0 0 0 0 0 0 1 1 2 1 0 0 0 0 0]
 [0 0 0 0 0 0 1 2 2 0 0 0 0 0 0]
 [0 0 0 0 0 0 2 2 2 1 0 0 0 0 0]
 [0 0 0 0 0 2 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]


In [49]:
class GUI:
    
    
    def __init__(self):
        
        self.board = gameboard()
        self.ai = AI()
        self.human = human()
        self.lastplay_black = (0,0)
        self.lastplay_white = (0,0)
        self.turn = 0
        self.retracted = False
        self.last_black = 0
        self.last_white = 0
        self.record = []
        self.info = self.read_info().split(',')
        if self.info == ['']:
            self.user = ''
            self.contact = ''
        else:
            self.user = self.info[0]
            self.contact = self.info[1]
        self.cell_size = 30
        self.margin = 60 
        self.piece_size = 12
        self.window = tk.Tk()
        self.window.title('F. I. R.')
        self.window.geometry('760x520')
        self.window.resizable(0,0)
        self.history = self.loading_history()
        self.canvas = self.loading_main()
        self.e = self.loading_info()
        self.window.mainloop()
    
    def loading_history(self): 
        #划分区域
        frame_history = tk.Frame(self.window)
        frame_history.grid(row = 0, column = 1)
        #创建历史记录区
        tk.Button(frame_history,text = 'Retract', command = self.retract, padx = 33,pady = 3).grid(row = 0, column = 0)
        tk.Button(frame_history,text = 'Restart', command = self.restart, padx = 33,pady = 3).grid(row = 0, column = 1)
        scrollbar = tk.Scrollbar(frame_history,width = 10,relief = 'ridge')
        history = tk.Listbox(frame_history,width = 25, height = 18,relief = 'ridge', bd = 3 , yscrollcommand = scrollbar.set)#.set绑定滑块和listbox   
        scrollbar.config(command = history.yview)
        history.grid(row = 1, column = 0,columnspan = 2)
        scrollbar.grid(row = 1, column = 2, ipady = 125)
        return history
    
    def update_history(self,x):
        self.history.insert('end', str(x))

    def retract(self):
        self.canvas.delete(self.last_black)
        self.canvas.delete(self.last_white)
        self.turn -= 2
        self.board.empty_one(self.lastplay_black[0],self.lastplay_black[1])
        self.board.empty_one(self.lastplay_white[0],self.lastplay_white[1])
        self.record.pop()
        self.record.pop()
        self.update_history('---Player retracted---')
        self.retracted = True
        print(self.board.get_board())
        
    def restart(self):
        self.window.destroy()
        GUI.__init__(self)
        
    def loading_info(self):
        frame_info = tk.Frame(self.window)
        frame_info.grid(row = 1, column = 1)
        frame_info.propagate(0)
        #创建信息区
        var = tk.StringVar()
        var.set('A Small Step Of The Great AI Dream\nProgram: Alpha Yi\nVersion: 1.0\nContributor:'+str(self.user)+'\nContact:'+str(self.contact))    
        l1 = tk.Label(frame_info, textvariable = var, bg = 'white', relief = 'ridge',width = 10,height = 2,bd = 3, padx = 73, pady = 30)
        l1.grid(row = 1, column = 0, columnspan = 2)
        tk.Label(frame_info, text = 'NickName:' ).grid(row = 2, column = 0)
        e1 = tk.Entry(frame_info, show = None, width = 15)
        e1.grid(row = 2, column = 1)
        tk.Label(frame_info, text = 'Email/Wechat:').grid(row = 3, column = 0)
        e2 = tk.Entry(frame_info, show = None, width = 15)
        e2.grid(row = 3, column = 1)
        tk.Button(frame_info, text = 'Click to comfirm',padx=19, command = self.update_info).grid(row = 4, column = 1)
        tk.Label(frame_info, text = '(Optional)').grid(row = 4, column = 0)
        return (e1,e2,var)
        
    def update_info(self):
        self.user = self.e[0].get()
        self.contact = self.e[1].get()
        self.save_info()
        print(self.contact)
        self.e[2].set('A Small Step Of The Great AI Dream\nProgram: Alpha Yi\nVersion: 1.0\nContributor:'+str(self.user)+'\nContact:'+str(self.contact))

    
    def loading_main(self):
        #划分区域
        frame_main = tk.Frame(self.window)
        frame_main.grid(row = 0, column = 0, rowspan = 2)
        canvas = tk.Canvas(frame_main, bg = 'yellow', height = self.margin*1.5+14*self.cell_size, width = self.margin*1.5+14*self.cell_size)
        canvas.grid(row = 1, column = 1)
        x1,y1,x2,y2 = self.margin,self.margin,self.margin,self.margin+14*self.cell_size
        for i in range(0,15):
            canvas.create_line(x1+i*self.cell_size,y1,x2+i*self.cell_size,y2)
            tk.Label(frame_main,text = str(i), bg = 'yellow', fg = 'black').place(x = x1+i*self.cell_size, y = y1-self.margin*0.5, anchor = 'center')   
        x3,y3,x4,y4 = self.margin,self.margin,self.margin+14*self.cell_size,self.margin
        for i in range(0,15):
            canvas.create_line(x3,y3+i*self.cell_size,x4,y4+i*self.cell_size)
            tk.Label(frame_main,text = str(i), bg = 'yellow', fg = 'black').place(x = x3-self.margin*0.5, y = y1+i*self.cell_size, anchor = 'center')
        x0,y0 = self.margin,self.margin    
        canvas.create_oval(x0+3*self.cell_size-3,y0+3*self.cell_size-3,x0+3*self.cell_size+3,y0+3*self.cell_size+3,fill = 'black')
        canvas.create_oval(x0+11*self.cell_size-3,y0+11*self.cell_size-3,x0+11*self.cell_size+3,y0+11*self.cell_size+3,fill = 'black')    
        canvas.create_oval(x0+11*self.cell_size-3,y0+3*self.cell_size-3,x0+11*self.cell_size+3,y0+3*self.cell_size+3,fill = 'black')    
        canvas.create_oval(x0+3*self.cell_size-3,y0+11*self.cell_size-3,x0+3*self.cell_size+3,y0+11*self.cell_size+3,fill = 'black')    
        canvas.create_oval(x0+7*self.cell_size-3,y0+7*self.cell_size-3,x0+7*self.cell_size+3,y0+7*self.cell_size+3,fill = 'black')
        canvas.bind("<Button-1>",self.click)
        return canvas
    

    
    
    def click(self,event):
        col = ceil((event.x - 45)/30)-1
        row = ceil((event.y - 45)/30)-1
        #if self.ingame:
        if col in range(15) and row in range(15):
            if not self.board.occupied(row,col):
                self.main(row,col)
    
    def pop_message(self):
        if self.ask_saving():
            self.save_record()
        if self.ask_restart():
            self.restart()
        else:
            self.window.destroy()
            os._exit(0)
        
    def main(self,row,col):
        if not self.board.end:
            self.black_turn(row,col)            
        else:
            self.pop_message()
        if not self.board.end:
            self.white_turn()
            
        else:
            self.pop_message()
    
    def black_turn(self,row,col):
        self.board.add_black_piece(row,col)
        self.blackpiece(col,row)
        self.update_history(str(self.turn) + 'black:' + str(row) + ',' + str(col))
        self.lastplay_black = (row,col)
        self.retracted = False
        self.record.append([str(self.turn),(row,col)])
        self.turn += 1
        self.board.if_end(row,col)
        
    def white_turn(self):
        row,col = self.ai.think(self.board)
        self.board.add_white_piece(row,col)
        self.whitepiece(col,row) 
        self.update_history(str(self.turn) + 'white:' + str(row) + ',' + str(col))
        self.lastplay_white = (row,col)
        self.record.append([str(self.turn),(row,col)])
        self.turn += 1
        self.board.if_end(row,col)
        print(self.board.get_board())

    
    def blackpiece(self,x,y):

        self.last_black = self.canvas.create_oval(self.margin+x*self.cell_size-self.piece_size,
                           self.margin+y*self.cell_size-self.piece_size,
                           self.margin+x*self.cell_size+self.piece_size,
                           self.margin+y*self.cell_size+self.piece_size, fill = 'black')   
        self.retracted = False
        self.coordinate = (x,y)


    def whitepiece(self,x,y):

        self.last_white = self.canvas.create_oval(self.margin+x*self.cell_size-self.piece_size,
                           self.margin+y*self.cell_size-self.piece_size,
                           self.margin+x*self.cell_size+self.piece_size,
                           self.margin+y*self.cell_size+self.piece_size, fill = 'white')
        self.retracted = False
        self.coordinate = (x,y)

    def ask_saving(self):
        return tk.messagebox.askokcancel(title='',message='Game ended, do you want to save the game record？')

    def ask_restart(self):
        return tk.messagebox.askokcancel(title='',message='Do you want to restart the game?')
    
    def save_record(self):
        file_name = strftime('%Y_%m_%d_%H_%M_%S.txt')
        dir_path = path.join(path.expanduser('~'),'Desktop','AlphaYi')
        fullpath = path.join(dir_path,file_name)
        with open(fullpath,mode = "w") as f:
            f.write(str(self.user) + ',' + str(self.contact) + ',' + str(self.record)) 
            
   
                    
    def read_info(self):
        file_name = strftime('info.txt')
        dir_path = path.join(path.expanduser('~'),'Desktop','AlphaYi')
        fullpath = path.join(dir_path,file_name)
        info = ''
        try:
            with open(fullpath) as r:
                 info = r.read()
        except:
            pass
        return info      
    
    def save_info(self):
        file_name = strftime('info.txt')
        dir_path = path.join(path.expanduser('~'),'Desktop','AlphaYi')
        fullpath = path.join(dir_path,file_name)
        with open(fullpath,mode = "w") as s:
            s.write(str(self.user) + ',' + str(self.contact))              
    
#     def loading_board(self,recording):
#         recording_cleaned = re.search("\[\'(.*)\)]",recording)
#         steps = re.findall("\(.*?\)",str(record_cleaned.group()))
#         for i in range(len(steps)):
#             if i % 2 = 0:
#                 self.board.add_black_piece(steps[i][0],steps[i][1])
#                 self.blackpiece(steps[i][1],steps[i][0])
#                 self.update_history(str(self.turn) + 'black:' + str(steps[i][0]) + ',' + str(step[i][1]))
#                 self.lastplay_black = (steps[i][0],steps[i][1])
#                 self.retracted = False
#                 self.record.append([str(self.turn),(steps[i][0],steps[i][1])])
#                 self.turn += 1
#                 self.board.if_end(steps[i][0],steps[i][1])
#             if i % 2 = 1:
#                 self.board.add_white_piece(steps[i][0],steps[i][1])
#                 self.whitepiece(steps[i][1],steps[i][0]) 
#                 self.update_history(str(self.turn) + 'white:' + str(steps[i][0]) + ',' + str(step[i][1]))
#                 self.lastplay_white = (steps[i][0],steps[i][1])
#                 self.record.append([str(self.turn),(steps[i][0],steps[i][1])])
#                 self.turn += 1
#                 self.board.if_end(steps[i][0],steps[i][1])
    
    
if __name__ == '__main__':    
    pass
    GUI = GUI()


[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 2 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
[[0 0 0 

In [9]:
class game:
    def __init__(self):
        self.board = gameboard()
        self.ai = AI()
        self.human = human()
        self.turn = 0
        self.record = []

    def main(self):
        if not self.board.end:
            self.black_turn()
            print(self.board.get_board())
        else:
            print("end,white win")
            
        if not self.board.end:
            self.white_turn()
            print(self.board.get_board())
        else:
            print("end,black win")
        
    def black_turn(self):
        row,col = self.human.ask_coordinate()
        self.board.add_black_piece(row,col)
        self.lastplay_black = (row,col)
        self.record.append([str(self.turn),(row,col)])
        self.turn += 1
        self.board.if_end(row,col)
        
    def white_turn(self):
        row,col = self.ai.ask_coordinate()
        self.board.add_white_piece(row,col)
        print(str(self.turn) + 'white:' + str(row) + ',' + str(col))
        self.lastplay_white = (row,col)
        self.record.append([str(self.turn),(row,col)])
        self.turn += 1
        self.board.if_end(row,col)
        
if __name__ == '__main__':     
    pass
#     game = game()
#     game.main()


In [52]:
dir_path = path.join(path.expanduser('~'),'Desktop','AlphaYi')
dir_path

'/Users/haofeng/Desktop/AlphaYi'